sudo: required
services:
    -docker

before_install:
    - docker build -t michalovsky/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true michalovsky/react-test npm test

after_success:
    - docker build -t michalovsky/multi-client ./client
    - docker build -t michalovsky/multi-nginx ./nginx
    - docker build -t michalovsky/multi-server ./server
    - docker build -t michalovsky/multi-worker ./worker
    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them into dockerhub
    - docker push michalovsky/multi-client
    - docker push michalovsky/multi-nginx
    - docker push michalovsky/multi-server
    - docker push michalovsky/multi-worker

deploy:
    edge: true
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "multi-docker"
    env: "MultiDocker-env"
    bucket_name: "elasticbeanstalk-us-east-2-977004637198"
    bucket_path: "docker-multi"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    